# Generated by Django 4.2 on 2023-04-25 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cotacao',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('data', models.DateField()),
                ('dolar', models.DecimalField(decimal_places=2, max_digits=5)),
                ('euro', models.DecimalField(decimal_places=2, max_digits=5)),
                ('yene', models.DecimalField(decimal_places=2, max_digits=5)),
                ('real', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
    ]
